apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:       #These labels are deployment labels
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:   #These labels are used to find the pods
      app: mongodb
      tier: db
  template:
    metadata:
      labels:      #These labels are pod labels
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: dockerhk2/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017



